version: "3"
services: 
  mongodb:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
  app:
    build:
      context: .
      args:
        name: "demo"
        version: "0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
