version: "3.7"
services: 
  mongodb:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
  app:
    build:
      context: .
      args:
        name: "demo"
        version: "0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mongodb:27017"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s
