apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  - name: "27018"
    port: 27018
    targetPort: 27018
  - name: "27019"
    port: 27019
    targetPort: 27019
  selector:
    io.kompose.service: mongodb
status:
  loadBalancer: {}
